version: "3.9"
services:
  recsys:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../artifacts:/app/artifacts
      - ../configs:/app/configs
